### ISSUE TITLE
TCSF-2.6.bash got [Error] seqtk failed, IMRA-2.6.bash got errors in seqinr and AssemblyEval.R

### ISSUE THREAD

**Issue by tomas-najer** [Yukihirokinjo/TCSF_IMRA#3]
Hello, kinjo,

 I am new to NGS data analysis and I have trouble running both TCSF and IMRA. I am pasting here what I got:

./TCSF-2.6.bash  -i SRR8334233-MH001227.SRR8334233_Amyrsidea-minuta-MH001227.1.all_contigs.fasta -refB Amyrsidea-minuta-MH001227.1.fasta

TCSF--------------------------------------------------- START_202107131132

Building a new DB, current time: 07/13/2021 11:32:08
New DB name:   /home/najer/TCSF_IMRA/TCSF_OUT_20210713_1132/DB/TCSF_DB.fna
New DB title:  TCSF_OUT_20210713_1132/DB/TCSF_DB.fna
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 1 sequences in 0.00323296 seconds.

Blast+ ---------------------------- START
Warning: [tblastx] Examining 5 or more matches is recommended
Blast parameters
Eval      = 
word_size = 3
num cpu   = 1

Blast+ ---------------------------- Finish

 ---------------------------- Generate Contig lists

 ---------------------------- Write TCSF FASTA File
./TCSF-2.6.bash: line 454: seqtk: command not found
[Error] seqtk failed. Please check the File.

./IMRA-2.6.bash  -ref Amyrsidea-minuta-MH001227.1.fasta -inF SRR8334233_1-trim-adapters-right.fastq -inR SRR8334233_2-trim-adapters-right.fastq -spa

IMRA--------------------------------------------------------Start.20210713114025

-----------Initial status

Error: package or namespace load failed for ‘seqinr’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/najer/TCSF_IMRA/Rlib/ade4/libs/ade4.so':
  libRlapack.so: unable to open shared object file: directory or file does not exist
Execution halted
[Error] AssemblyEval.R failed. Please check the Messages above

./IMRA-2.6.bash  -ref Amyrsidea-minuta-MH001227.1.fasta -inF SRR8334233_1-trim-adapters-right.fastq -inR SRR8334233_2-trim-adapters-right.fastq -spa -k 33,55,91,121

IMRA--------------------------------------------------------Start.20210713114122

-----------Initial status

Error: package or namespace load failed for ‘seqinr’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/najer/TCSF_IMRA/Rlib/ade4/libs/ade4.so':
  libRlapack.so: unable to open shared object file: directory or file does not exist
Execution halted
[Error] AssemblyEval.R failed. Please check the Messages above

I have, however, installed both the packages (seqtk, seqinr) and I see them in R. For instance, command seqinr::swap in R gives this:

seqinr::swap
function (x, y) 
{
    x.sub <- substitute(x)
    y.sub <- substitute(y)
    x.val <- x
    e <- parent.frame()
    do.call("<-", list(x.sub, y.sub), envir = e)
    do.call("<-", list(y.sub, x.val), envir = e)
}
<bytecode: 0x55e75fb255f8>
<environment: namespace:seqinr>

When I checked the AssemblyEval.R code, it is searching seqinr in LibDir directory, and manually I cannot find this directory anywhere, and I do not feel confident to touch the paths in the code. The R scripts are also added in my PATH (based on the previous issues here). So what can be wrong?

**Comment by Yukihirokinjo** [comment]
Hi Tom,

I am so sorry about the delayed response..

I have some questions.

  1.  Which OS are you working with?
  2.  Did you already install seqtk?

Regarding the error from TCSF, it seems that seqtk is not installed yet.
You can check whether seqtk is installed or not by typing the command below

which  seqtk

if the command above shows a path to the program, it is installed, otherwise it’s not.

Regarding the error from IMRA, it likely because of the AssemblyEval script.
So I have updated the scripts (v2.6 -> v2.7). Could you please re-install this tool?
In the new version, there is a new step in the installation procedure (need to set TCSF_IMRA environment variable).

If you still get errors, please let me know.
I will be much quicker than this time.

Best regards,
Kinjo

差出人: tomas-najer ***@***.***>
日付: 火曜日, 2021年7月13日 19:09
宛先: Yukihirokinjo/TCSF_IMRA ***@***.***>
CC: Subscribed ***@***.***>
件名: [Yukihirokinjo/TCSF_IMRA] TCSF-2.6.bash got [Error] seqtk failed, IMRA-2.6.bash got errors in seqinr and AssemblyEval.R (#3)

Hello, kinjo,

I am new to NGS data analysis and I have trouble running both TCSF and IMRA. I am pasting here what I got:

./TCSF-2.6.bash -i SRR8334233-MH001227.SRR8334233_Amyrsidea-minuta-MH001227.1.all_contigs.fasta -refB Amyrsidea-minuta-MH001227.1.fasta

TCSF--------------------------------------------------- START_202107131132

Building a new DB, current time: 07/13/2021 11:32:08
New DB name: /home/najer/TCSF_IMRA/TCSF_OUT_20210713_1132/DB/TCSF_DB.fna
New DB title: TCSF_OUT_20210713_1132/DB/TCSF_DB.fna
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 1 sequences in 0.00323296 seconds.

Blast+ ---------------------------- START
Warning: [tblastx] Examining 5 or more matches is recommended
Blast parameters
Eval =
word_size = 3
num cpu = 1

Blast+ ---------------------------- Finish

---------------------------- Generate Contig lists

---------------------------- Write TCSF FASTA File
./TCSF-2.6.bash: line 454: seqtk: command not found
[Error] seqtk failed. Please check the File.

./IMRA-2.6.bash -ref Amyrsidea-minuta-MH001227.1.fasta -inF SRR8334233_1-trim-adapters-right.fastq -inR SRR8334233_2-trim-adapters-right.fastq -spa

IMRA--------------------------------------------------------Start.20210713114025

-----------Initial status

Error: package or namespace load failed for ‘seqinr’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/home/najer/TCSF_IMRA/Rlib/ade4/libs/ade4.so':
libRlapack.so: unable to open shared object file: directory or file does not exist
Execution halted
[Error] AssemblyEval.R failed. Please check the Messages above

./IMRA-2.6.bash -ref Amyrsidea-minuta-MH001227.1.fasta -inF SRR8334233_1-trim-adapters-right.fastq -inR SRR8334233_2-trim-adapters-right.fastq -spa -k 33,55,91,121

IMRA--------------------------------------------------------Start.20210713114122

-----------Initial status

Error: package or namespace load failed for ‘seqinr’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/home/najer/TCSF_IMRA/Rlib/ade4/libs/ade4.so':
libRlapack.so: unable to open shared object file: directory or file does not exist
Execution halted
[Error] AssemblyEval.R failed. Please check the Messages above

I have, however, installed both the packages (seqtk, seqinr) and I see them in R. For instance, command seqinr::swap in R gives this:

seqinr::swap
function (x, y)
{
x.sub <- substitute(x)
y.sub <- substitute(y)
x.val <- x
e <- parent.frame()
do.call("<-", list(x.sub, y.sub), envir = e)
do.call("<-", list(y.sub, x.val), envir = e)
}
<bytecode: 0x55e75fb255f8>
<environment: namespace:seqinr>

When I checked the AssemblyEval.R code, it is searching seqinr in LibDir directory, and manually I cannot find this directory anywhere, and I do not feel confident to touch the paths in the code. The R scripts are also added in my PATH (based on the previous issues here). So what can be wrong?

**Comment by tomas-najer** [comment]
Hi Kinjo,

don't worry about the delay, I am also not fast.

1. Ubuntu 21.04
2. This problem is solved, thanks. I thought I have installed seqtk, but the command "which" did not see it, so I have reinstalled it - that is fixed now.

However, now I have a problem setting the TCSF_IMRA environment variable. I have used commands:

echo 'TCSF_IMRA==/path/to/TCSF_IMRA_dir' >> ~/.bashrc
source ~/.bashrc

It does not write anything, so I assumed everything is fine, but when I try to run TCSF, I get:

[Error] The environment variable TCSF_IMRA is not set.

So how can I check if it's properly set, and how to set it by another way?

Thank you so much,
Tom

**Comment by Yukihirokinjo** [comment]
Hi Tom,

Sorry again, there was a typo in the README regarding the TCSF_IMRA environment variable (“==” should be “=”).

Please retry that with
echo  'TCSF_IMRA=/path/to/TCSF_IMRA_dir' >> ~/.bashrc

Although it is not necessary, I recommend you to delete the redundant lines you have already added in the previous installations from ~/.bashrc.
You can use text editor to do that. I guess there are four or five lines

export PATH=/path/to/TCSF_IMRA_dir:$PATH
export PATH=/path/to/TCSF_IMRA_dir:$PATH
TCSF_IMRA==/path/to/TCSF_IMRA_dir
TCSF_IMRA=/path/to/TCSF_IMRA_dir

Then you can remove 1st and 3rd lines, of course 2nd and 4th lines must be kept.

export PATH=/path/to/TCSF_IMRA_dir:$PATH
TCSF_IMRA=/path/to/TCSF_IMRA_dir

This is just to keep ~/.bashrc clean and secure.
Note that .bashrc file is in your home directory as a hidden file (starting from “.”). If you checking it via GUI environment, probably you need to change a setting of file manager (like Finder in MacOS) to make the hidden files visible.

Best,
Kinjo



差出人: tomas-najer ***@***.***>
日付: 火曜日, 2021年7月20日 0:27
宛先: Yukihirokinjo/TCSF_IMRA ***@***.***>
CC: Yukihiro Kinjo <YUKIHIRO.KINJO@OIST.JP>, Comment ***@***.***>
件名: Re: [Yukihirokinjo/TCSF_IMRA] TCSF-2.6.bash got [Error] seqtk failed, IMRA-2.6.bash got errors in seqinr and AssemblyEval.R (#3)

Hi Kinjo,

don't worry about the delay, I am also not fast.

  1.  Ubuntu 21.04
  2.  This problem is solved, thanks. I thought I have installed seqtk, but the command "which" did not see it, so I have reinstalled it - that is fixed now.

However, now I have a problem setting the TCSF_IMRA environment variable. I have used commands:

echo 'TCSF_IMRA==/path/to/TCSF_IMRA_dir' >> ~/.bashrc
source ~/.bashrc

It does not write anything, so I assumed everything is fine, but when I try to run TCSF, I get:

[Error] The environment variable TCSF_IMRA is not set.

So how can I check if it's properly set, and how to set it by another way?

Thank you so much,
Tom

**Comment by tomas-najer** [comment]
Hi Kinjo,

Thank you so much, but this is what I assumed, I have tried also "=" instead of "==", so it looks exactly as you say (in my case):

export PATH=/home/najer/TCSF_IMRA:$PATH
TCSF_IMRA=/home/najer/TCSF_IMRA

And after "source ~/.bashrc", it still writes "[Error] The environment variable TCSF_IMRA is not set." So I think my system somehow cannot see the variable, but I do not know why and how to fix it.

Thanks,
Tom

**Comment by Yukihirokinjo** [comment]
Hi Tom,

Sorry I found an error in my scripts.
I have fixed it then the new IMRA works correctly in my test environment.
Could you please re-install the new version (2.7.1)?
The installation procedure is the same with previous one.

Best,
Kinjo

差出人: tomas-najer ***@***.***>
日付: 水曜日, 2021年7月21日 0:22
宛先: Yukihirokinjo/TCSF_IMRA ***@***.***>
CC: Yukihiro Kinjo <YUKIHIRO.KINJO@OIST.JP>, Comment ***@***.***>
件名: Re: [Yukihirokinjo/TCSF_IMRA] TCSF-2.6.bash got [Error] seqtk failed, IMRA-2.6.bash got errors in seqinr and AssemblyEval.R (#3)

Hi Kinjo,

Thank you so much, but this is what I assumed, I have tried also "=" instead of "==", so it looks exactly as you say (in my case):

export PATH=/home/najer/TCSF_IMRA:$PATH
TCSF_IMRA=/home/najer/TCSF_IMRA

And after "source ~/.bashrc", it still writes "[Error] The environment variable TCSF_IMRA is not set." So I think my system somehow cannot see the variable, but I do not know why and how to fix it.

Thanks,
Tom

**Comment by tomas-najer** [comment]
Hi Kinjo,

I am sorry, but I have reinstalled it, set up the variable again, and still the same error:

[Error] The environment variable TCSF_IMRA is not set.

Thanks,
Tom

**Comment by Yukihirokinjo** [comment]
Hi Tom,

Could you please check the results of the commands below?

echo  $TCSF_IMRA

which IMRA-2.7.1.bash

Of course you don’t need to show the exact path to IMRA-2.7.1.bash here. Just to confirm whether it is actually in the PATH.

Best,
Kinjo

差出人: tomas-najer ***@***.***>
日付: 木曜日, 2021年7月22日 17:15
宛先: Yukihirokinjo/TCSF_IMRA ***@***.***>
CC: Yukihiro Kinjo <YUKIHIRO.KINJO@OIST.JP>, Comment ***@***.***>
件名: Re: [Yukihirokinjo/TCSF_IMRA] TCSF-2.6.bash got [Error] seqtk failed, IMRA-2.6.bash got errors in seqinr and AssemblyEval.R (#3)

Hi Kinjo,

I am sorry, but I have reinstalled it, set up the variable again, and still the same error:

[Error] The environment variable TCSF_IMRA is not set.

Thanks,
Tom

**Comment by tomas-najer** [comment]
Hi Kinjo,

Thanks for the message, it’s no problem to show the way:

echo $TCSF_IMRA : /home/najer/TCSF_IMRA

which IMRA-2.7.1.bash :  /home/najer/TCSF_IMRA/IMRA-2.7.1.bash

Thank you in advance,
Tom

**Comment by Yukihirokinjo** [comment]
Hi Tom,

OK.
Did you get the error from IMRA?, or TCSF?

Best,
Kinjo
差出人: tomas-najer ***@***.***>
日付: 金曜日, 2021年7月23日 17:49
宛先: Yukihirokinjo/TCSF_IMRA ***@***.***>
CC: Yukihiro Kinjo <YUKIHIRO.KINJO@OIST.JP>, Comment ***@***.***>
件名: Re: [Yukihirokinjo/TCSF_IMRA] TCSF-2.6.bash got [Error] seqtk failed, IMRA-2.6.bash got errors in seqinr and AssemblyEval.R (#3)
Hi Kinjo,

Thanks for the message, it’s no problem to show the way:

echo $TCSF_IMRA : /home/najer/TCSF_IMRA

which IMRA-2.7.1.bash : /home/najer/TCSF_IMRA/IMRA-2.7.1.bash

Thank you in advance,
Tom

**Comment by tomas-najer** [comment]
Hi Kinjo,

yes, both TCSF and IMRA still give [Error] The environment variable TCSF_IMRA is not set.

Thanks,
Tom

**Comment by Yukihirokinjo** [comment]
Hi Tom,

What about “Location of TCSF_IMRA:”? Does this show proper location like below?

  “Location of TCSF_IMRA: /home/najer/TCSF_IMRA”

Could you please show me the command and stdout including the error message?

Best,
Kinjo

差出人: tomas-najer ***@***.***>
日付: 金曜日, 2021年7月23日 18:30
宛先: Yukihirokinjo/TCSF_IMRA ***@***.***>
CC: Yukihiro Kinjo <YUKIHIRO.KINJO@OIST.JP>, Comment ***@***.***>
件名: Re: [Yukihirokinjo/TCSF_IMRA] TCSF-2.6.bash got [Error] seqtk failed, IMRA-2.6.bash got errors in seqinr and AssemblyEval.R (#3)

Hi Kinjo,

yes, both TCSF and IMRA still give [Error] The environment variable TCSF_IMRA is not set.

Thanks,
Tom

**Comment by tomas-najer** [comment]
Hi Kinjo,

it gives: Location: command not found

The commands I was trying were:

TCSF-2.7.1.bash  -i example_dataset/input_contigs.fna -refB example_dataset/reference_bacterial_genome.fna
./TCSF-2.7.1.bash  -i example_dataset/input_contigs.fna -refB example_dataset/reference_bacterial_genome.fna
IMRA-2.7.1.bash  -ref example_dataset/input_contigs.fna -inF example_dataset/input_read_1.fastq -inR example_dataset/input_read_2.fastq -spa
./IMRA-2.7.1.bash  -ref example_dataset/input_contigs.fna -inF example_dataset/input_read_1.fastq -inR example_dataset/input_read_2.fastq -spa

The whole stdout is:
Location of TCSF_IMRA: 
[Error] The environment variable TCSF_IMRA is not set.

I am sending a printscreen, hopefully it helps.
![Screenshot-2021-07-23-15-47-18](https://user-images.githubusercontent.com/80354578/126791587-9063670a-c5e9-4ec0-b13b-e16bfea28def.png)

Thank you a lot,
Tom

**Comment by Yukihirokinjo** [comment]
Hi Tom,

So sorry. I found out a mistake in my README.

Plase add “export” when you add TCSF_IMRA environment variable into your ~/.bashrc.

echo 'export TCSF_IMRA=/path/to/TCSF_IMRA_dir' >> ~/.bashrc

So sorry again for this mistake.

Best,
Kinjo


差出人: tomas-najer ***@***.***>
日付: 金曜日, 2021年7月23日 22:51
宛先: Yukihirokinjo/TCSF_IMRA ***@***.***>
CC: Yukihiro Kinjo <YUKIHIRO.KINJO@OIST.JP>, Comment ***@***.***>
件名: Re: [Yukihirokinjo/TCSF_IMRA] TCSF-2.6.bash got [Error] seqtk failed, IMRA-2.6.bash got errors in seqinr and AssemblyEval.R (#3)

Hi Kinjo,

it gives: Location: command not found

The commands I was trying were:

TCSF-2.7.1.bash -i example_dataset/input_contigs.fna -refB example_dataset/reference_bacterial_genome.fna
./TCSF-2.7.1.bash -i example_dataset/input_contigs.fna -refB example_dataset/reference_bacterial_genome.fna
IMRA-2.7.1.bash -ref example_dataset/input_contigs.fna -inF example_dataset/input_read_1.fastq -inR example_dataset/input_read_2.fastq -spa
./IMRA-2.7.1.bash -ref example_dataset/input_contigs.fna -inF example_dataset/input_read_1.fastq -inR example_dataset/input_read_2.fastq -spa

The whole stdout is:
Location of TCSF_IMRA:
[Error] The environment variable TCSF_IMRA is not set.

I am sending a printscreen, hopefully it helps.
[Screenshot-2021-07-23-15-47-18]<https://user-images.githubusercontent.com/80354578/126791587-9063670a-c5e9-4ec0-b13b-e16bfea28def.png>

Thank you a lot,
Tom

**Comment by tomas-najer** [comment]
Hi Kinjo,

Aha, I got it, thank you so much! Now both TCSF & IMRA work without problem, thank you again!

Tom
